### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by tooolbox** [khell/homebrew-srm#1]
I'm running Catalina.

```
> brew install khell/homebrew-srm/srm
==> Tapping khell/srm
Cloning into '/usr/local/Homebrew/Library/Taps/khell/homebrew-srm'...
remote: Enumerating objects: 10, done.
remote: Total 10 (delta 0), reused 0 (delta 0), pack-reused 10
Unpacking objects: 100% (10/10), done.
Tapped 1 formula (35 files, 29.3KB).
==> Installing srm from khell/srm
==> Downloading https://homebrew.bintray.com/bottles-srm/srm-1.2.15.sierra.bottle.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "srm"
Download failed: https://homebrew.bintray.com/bottles-srm/srm-1.2.15.sierra.bottle.tar.gz
```

I think I can just download from SourceForge and `make` but wanted to FYI you.  Thanks for standing up for our rights btw :)

**Comment by branthom** [comment]
@tooolbox This may have something to do with the [formula](https://github.com/khell/homebrew-srm/blob/master/Formula/srm.rb) that has not been updated past Sierra (10.12). Try:

`brew install --build-from-source khell/homebrew-srm/srm`

Note to self:
404 Not Found:
https://homebrew.bintray.com/bottles-srm/srm-1.2.15.sierra.bottle.tar.gz
200 OK:
https://dl.bintray.com/homebrew/bottles/srm-1.2.15.sierra.bottle.tar.gz
