### ISSUE TITLE
404 on srm_bottle_manifest

### ISSUE THREAD

**Issue by hbxc0re** [khell/homebrew-srm#3]
Won't install please fix this, thanks.
==> Downloading https://ghcr.io/v2/homebrew/core/srm/manifests/1.2.15
curl: (22) The requested URL returned error: 404

**Comment by khell** [comment]
Hi, I'm a little late but I've just tested this and it works fine. In your error, you are getting a `404` response and the URL you are downloading from is definitely wrong as that points to the main homebrew repo. Please ensure you are running the command in the README:
`brew install khell/homebrew-srm/srm`

Feel free to reopen if this is not the case.
